version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7
      - image: circleci/postgres:9.4-alpine-postgis
    steps:
      - checkout
      - run:
          name: Setup Python environment
          command: |
            sudo apt-get update && sudo apt-get install python-gdal
            pip install virtualenv
            virtualenv env-ci

      - restore_cache:
          keys:
            - pip-v1-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/development.txt" }}
            - pip-v1-
      - run:
          name: Install dependencies
          command: |
            source env-ci/bin/activate
            pip install --requirement requirements/base.txt --requirement requirements/development.txt
      - save_cache:
          key: pip-v1-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "~/.cache/pip"

      - run:
          name: Run unit tests
          command: |
            source env-ci/bin/activate
            python manage.py test

workflows:
  version: 2
  test:
    jobs:
      - test
